version: "3.7"
services:
  products:
    image: mongo:5.0.9-focal
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PRODUCT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PRODUCT_DB_PWD}
      MONGO_INITDB_DATABASE: products
    ports:
      - 27017:27017
    volumes:
      - ./initdata/products-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  activemq:
    image: webcenter/activemq:5.14.3
    container_name: broker
    restart: always
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
