server:
  port: 8761
spring:
  application:
    name: discovery
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  level:
    com:
      netflix:
        discovery: OFF
        eureka: OFF
